const levelMaps = [
  ['                                                                          ',
  '                                                          ',
    '               z        r       o      e   ',
    '                                           ',    
    '                                           ',
    '                                           ',    
    '                                           ',    
    '                                           ',    
    '               Z        @       O      E   ',    
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                           ',    
    '                                           ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '                                                        ',    
    '               xxxxxxxxxxxxxxxxxxxxxx                                ',
    '               x   0                x                  ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x       i            x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    xxxxxxxxxxxxxxxxxx                   ',
    '               x                                     x                   ',
    '               x                                     x                   ',
    '               x                                     x                   ',
    '               x                                     x                    ',
    '               x                                     x   ',
    '               x                           !         x   ',
    '               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ',
    '                       ',
    '       1               ',
    '                       ',
    '                       ',
    '                       ',
    '                       ',
  ],

  ['                                                                         ',
  '                                                          ',
    '               z        r       o      e   ',
    '                                           ',    
    '                                           ',
    '                                           ',    
    '                                           ',    
    '                                           ',    
    '               Z        @       O      E   ',    
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                           ',    
    '                                           ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',    
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xx  2                                                                xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',   
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx       i                                                        !  xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx                                                                   xxx',
    'xx                     xxxxx                 xxx                     xxx',
    'xx                     xxxxx                                         xxx',
    'xx                     xxxxx                                         xxx',
    'xx                 xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxx             xxxxxxxxx                                         xxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  ],

  [ 'xxxxxxxxxxxxxx        z        r       o      e    xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx        Z        @       O      E    xxxxxxxxxx',    
    'xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',    
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx          h                          xxxxxxxxxx',
    'xxxxxxxxxxxxxx     h          h          h         xxxxxxxxxx',
    'xxxxxxxxxxxxxx        h    h       h            h  xxxxxxxxxx',
    'xxxxxxxxxxxxxx   h                      h          xxxxxxxxxx',
    'xxxxxxxxxxxxxx           h     h    h              xxxxxxxxxx',
    'xxxxxxxxxxxxxx     h             h         h   h   xxxxxxxxxx',
    'xxxxxxxxxxxxxx              h        h             xxxxxxxxxx',
    'xxxxxxxxxxxxxx    h   h         h        h         xxxxxxxxxx',
    'xxxxxxxxxxxxxx      h         h    h          h    xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
    'xxxxxxxxxxxxxx          !                          xxxxxxxxxx',
    'xxxxxxxxxxxx            xx                         xxxxxxxxxx',
    'xxxxxxxxxxxx            xx                         xxxxxxxxxx',   
    'xxxxxxxxxxxx                                       xxxxxxxxxx',  
    'xxxxxxxxxxxx                                       xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                       xxxxxxxx',  
    'xxxxxxxxxxxxxx                                       xxxxxxxx',   
    'xxxxxxxxxxxxxx                           xx          xxxxxxxx',  
    'xxxxxxxxxxxxxx  xx                       xx          xxxxxxxx',   
    'xxxxxxxxxxxxxx  xx               xx                  xxxxxxxx',  
    'xxxxxxxxxxxxxx                   xx                xxxxxxxxxx',   
    'xxxxxxxxxxxxxx       xx                            xxxxxxxxxx',  
    'xxxxxxxxxxxxxx       xx                            xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                 xxxxxxxxxxxxxx',  
    'xxxxxxxxxxxxxx                                 xxxxxxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',  
    'xxxxxxxxxxxxxx                      xx             xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                      xx             xxxxxxxxxx',   
    'xxxxxxxxxxxxxx              xx                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx              xx                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx    xx                               xxxxxxxxxx',   
    'xxxxxxxxxxxxxx    xx                               xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx            xx           xx          xxxxxxxxxx',   
    'xxxxxxxxxxxxxx            xx           xx          xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                                     xxxxxxxxxx',   
    'xxxxxxxxxxxxxx                          i        xxxxxxxxxxxx',
    'xxxxxxxxxxxxxx                                   xxxxxxxxxxxx',
    'xxxxxxxxxxxxxx                                   xxxxxxxxxxxx',    
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  ],

  ['                                             ',
  '                                              ',
    '               z               o      e     ',
    '                                            ',    
    '                                            ',
    '                                            ',    
    '                                            ',    
    '                                            ',    
    '               Z               O      E     ',    
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    '                                            ',    
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '         3                   4              ',
    '                                            ',
    '     i                              r       ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '         @                      !           ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  ],
  

  ['                                                                               ',
  '                                                                                ',
    '               z               o      e                                       ',
    '                                                                              ',    
    '                                                                              ',
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '               Z               O      E                                       ',    
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                   ',
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                              ',    
    '                 @                                                             ',    
    '                                                                              ',    
    '                                                                              ',    
    '                                                                             ',    
    '                                                                              ',
    '             i                                                                        ',
    '                                                                              ',
    '                                                                              ',
    '             xxxxxxx! xxxxxxxxxxx                                                                      ',
    'xxx          xxxxxxxxxxxxxxxxxxxx                                             ',
    'xxx                             x                                                 ',
    'xxxxx                           x                                                 ',
    'xxxxx                           x                                                 ',
    'xxxxxxx                         x                 r                                ',
    'xxxxxxx                         x                                                 ',
    'x                               x                                                 ',
    'x                               x                                                  ',
    'x                               x                                                 ',
    'x            xxxx               x                                               ',
    'x            xxxx               x                                                 ',
    'x                               x                                               ',
    'x                               x                                           ',
    'x                           xxxxx                                                 ',
    'x                           xxxxx                                                 ',
    'x                xx         xxxxx                                                 ',
    'x                xx         xxxxx                                                 ',
    'x              xxxx             x                                   ',
    'x              xxxx             x                                    ',
    'x              xxxx             x                                    ',
    'x              xxxx             x                                    ',
    'xxxxx                                                                              ',
    'xxxxx                                                                               ',
    'xxxxx                                                                              ',
    'xxxxx                                                                             ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  ],

  [ '                                             ',
    '                                             ',
    '               z             e              ',
    '                                             ',    
    '                                             ',
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '               Z             E              ',    
    '           xxxxxxxxxxxxxxxxxxxxxxxx          ',
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '                                             ',    
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxx5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'x                                         o x',    
    'x                                           x',    
    'x    i         r                            x',    
    'x                                           x',    
    'x                                           x',    
    'x                                           x',    
    'x    O                               !  @   x',    
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',                                                               
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '                                             ',    
    '                                                                              '
  ],
  [ 'x                                             ',
    'x                                              ',
    'x               z                      e     ',
    'x                                            ',    
    'x                                            ',
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x               Z                      E     ',    
    'x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    'x                                            ',    
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x      O                                    x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                       L                   x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                      @     x',
    'x                                           x',
    'x                                           x',
    'x                                        !  x',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                                    xxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x              o              xxxxxxxxxxxxxxx',
    'x                             xxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x     i   r           xxxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

  [
    'x                                                                                                          ',
    'x                                              ',
    'x               z                           ',
    'x                                            ',    
    'x                                            ',
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x               Z                           ',    
    'x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x                                            ',    
    'x            i                                ',    
    'x                                            ',    
    'x            r                                ',    
    'x                                            ',    
    'x    i       o                                ',    
    'x                                                                                                                 ',    
    'x  R                                                                             e                                  ',    
    'x                                                                                                                 ',    
    'x                                                                                                    ',    
    'x  O                                                                             E                     ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    ],

    [ "x                                                                                                      ",
      "x             x                                          ",
      "x             x                                                                                  ",
      "x             x                                                                                    ",
      "x             x                                                                                  ",
      "x             x                                                                       xxxxxxxxxxxxxxx              ",
      "x             x                                                                       x             x           ",
      "x             x                                                                       x   !   @     x      ",
      "x             x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxx             x      ",
      "x             x      x                                 x              x                             x ",
      "x             x      x                      7          x              x                             x  ",
      "x             x      x                                 x              x                             x   ",
      "x             x      x                                 x              x                   t   t     x   ",
      "x             x      x       xxxxxxxxxxxxxxxxxxx       x              x ggggg xxxxxxxxxxxxxxxxxxxxxxx     ",
      "x             x      x ggggg x                 x       x              x ggggg x      ",
      "x             x      x ggggg x                 x       x              x ggggg x",
      "x             x      x ggggg x                 x       x              x ggggg x",
      "x             x      x ggggg x                 x       x              x ggggg x ",
      "x             xxxxxxxx ggggg x                 x       xxxxxxxxxxxxxxxx ggggg x",
      "x                      ggggg x                 x                        ggggg x                                       x",
      "x   i  r         6     ggggg x                 x                        ggggg x",
      "x                            x                 x                        ggggg x",
      "x                            x                 x                        ggggg x",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
],

 [        "                                                                             ",
          " x                                                                  x        x",   
          " x                                                                  x         x",
          " x   8                                                              x         x",
          " x                                                                  x        x",
          " x   i    r                                                         x            x",
          " x                                                                  x        x",
          " xxxxxxxxxxxxx           xxx             xxx                    ! @ x                    x",
          " xxxxxxxxxxxxx                                              xxxxxxxxx                     x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx                   x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwww9wwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxppppppppppppppppppppppppppppppppppppppppppxxxxxxxxxxxxx",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
[         "x             x                                            ",
          "x    i    r   x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "xp  ppppppppppx",
          "x             x",
          "x   ~         x",
          "x             x          #",
          "x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x                |   v   |   v   |   v  =|   |   v =   x",
          "x                  v   v    v   v   v  =v   |   v   =  x",
          "x     !                                            @   x",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
],

      [  "                                                                                             r  ",
          " x                                                                                        x  @ x",   
          " x                                                                                        xxxxxx",
          " x                                                               x",
          " x               x                                x              x",
          " x                              x                          x     x",
          " x           x                            x                      x",
          " x                      x                            x           x",
          " x                                           x                   x",
          " x               $                  x                            x",
          " x                            x                           x      x",
          " x i                                                             x",
          " x                                                           !   x",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],

      [  "                                                           r  ",
          " x                                     x                x  @ x",   
          " x                                     x                xxxxxx",
          " x                                     x",
          " x              xhh ! hhx              x",
          " x             xhhhh hhhhx     t       x",
          " x             xhhhhhhhhhx             x",
          " x             xxhhhhhhhxx             x",
          " x              xxhhhhhxx              x",
          " x   %           xxhhhxx    t          x",
          " x                xxhxx                x",
          " x i               xxx                 x",
          " x                                     x",    
          " x                             t       x",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
[         "                                                                          r      ",
          " x                                                                  x     @     x",   
          " x                                                                  x   xxxxxxxxx         x",
          " x   ^                                                              x         x",
          " x                                                                  x        x",
          " x   i                                                              x            x",
          " x                                                                  x        x",
          " xxxxxxxxxxxxx           xxx             xxx                    !   x                    x",
          " xxxxxxxxxxxxx                                              xxxxxxxxx                     x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx                   x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxppppppppppppppppppppppppppppppppppppppppppxxxxxxxxxxxxx",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],

[       "xxxxxxxxxxxxxxxxxx                                                       ",
        "x                x                                          ",
        "x      !         x                                         ",
        "x                x                               r         ",
        "x                x                               @          ",
        "x                x                                         ",
        "x                x",
        "x                x                                          ",
        "x                x                                        ",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x   i    &       x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                xxxxxxxxxxxxxxxx",
        "x               *               x",
        "x                               x",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
],

      [   " )                                                      @ ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x                                         x",
          "x                                      !  x",
          "x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x    i    r   x",
          "x (           x",
          "xxxxxxxxxxxxxxx"]
    
  ];
    
    
export default levelMaps;