const levelMaps = [
  [
    '                                                                          ',
    '                                                          ',
    '               z        r       o      e   ',
    '                                           ',
    '                                           ',
    '                                           ',
    '                                           ',
    '                                           ',
    '               Z        @       O      E   ',
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                           ',
    '                                           ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '                                                        ',
    '               xxxxxxxxxxxxxxxxxxxxxx                   ',
    '               x   0                x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x       i            x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    x                   ',
    '               x                    xxxxxxxxxxxxxxxxxx                   ',
    '               x                                     x                   ',
    '               x                                     x                   ',
    '               x                                     x                   ',
    '               x                                     x                    ',
    '               x                                     x   ',
    '               x                           !         x   ',
    '               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ',
    '                       ',
    '       1               ',
    '                       ',
    '                       ',
    '                       ',
    '                       '
  ],

  [
    '                                                                         ',
    '                                                          ',
    '               z        r       o      e   ',
    '                                           ',
    '                                           ',
    '                                           ',
    '                                           ',
    '                                           ',
    '               Z        @       O      E   ',
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                           ',
    '                                           ',
    '                                           ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xx  2                                                                xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx       i                                                        !  xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                                                                   xxxxxxxxxx',
    'xx                  xxxxxxxx               xxxxxxx                   xxxxxxxxxx',
    'xx                  xxxxxxxx                                         xxxxxxxxxx',
    'xx                  xxxxxxxx                                         xxxxxxxxxx',
    'xx              xxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxpppppppppppppppppppppppppppppppppppppppppxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxpppppppppppppppppppppppppppppppppppppppppxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  // [ 'xxxxxxxxxxxxxx        z        r       o      e    xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx        Z        @       O      E    xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx           v                         xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                            v        xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx  v                                  xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                 v                   xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                 v   xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx      v                              xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                       v             xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx          !                          xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx          xx                         xxxxxxxxxx',
  //   'xxxxxxxxxxxx            xx                         xxxxxxxxxx',
  //   'xxxxxxxxxxxx                                       xxxxxxxxxx',
  //   'xxxxxxxxxxxx                                       xxxxxxxxxx',
  //   'xxxxxxxxxxxx                                       xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                       xxxxxxxx',
  //   'xxxxxxxxxxxxxx                           xx          xxxxxxxx',
  //   'xxxxxxxxxxxxxx                           xx          xxxxxxxx',
  //   'xxxxxxxxxxxxxx  xx                                   xxxxxxxx',
  //   'xxxxxxxxxxxxxx  xx               xx                  xxxxxxxx',
  //   'xxxxxxxxxxxxxx                   xx                xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx       xx                            xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx       xx                            xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                 xxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                 xxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                      xx             xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                      xx             xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx              xx                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx              xx                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx    xx                               xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx    xx                               xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                     xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx            xx                  i    xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx            xx           xx          xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                         xx          xxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                   xxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                   xxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxx                                   xxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  //   'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  // ],

  [
    '                                             ',
    '                                              ',
    '               z               o      e     ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '               Z               O      E     ',
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '         3                   4              ',
    '                                            ',
    '     i                              r       ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '                                            ',
    '         @                      !           ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    '                                                                               ',
    '                                                                                ',
    '               z               o      e                                       ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '               Z               O      E                                       ',
    '           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                   ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                              ',
    '                                                                             ',
    '                                                                              ',
    '                i                                                                      ',
    '                                                                              ',
    '                                                                              ',
    '             xxxxxxxxxxxxxxxxxxxxx                                                                      ',
    '             xxxxxxxxxxxxxxxxxxxxx                                            ',
    '                                 x                                                ',
    'xxx                              x                                             ',
    'xxx                              x                                                 ',
    'xxxxx                            x                                                 ',
    'xxxxx                            x              xttttttx                                   ',
    'xxxxxxx                          x              xxxxxxxx                                   ',
    'xxxxxxx                          x                                                 ',
    'x                                x                                                 ',
    'x                                x                 r                                 ',
    'x             !                  x                                                 ',
    'x          xxxxxx                x                                               ',
    'x          xxxxxx                x                                                ',
    'x                                x                                              ',
    'x                            @   x                                           ',
    'x                           xxxxxx                                                 ',
    'x                           xxxxxx                                                 ',
    'x                           xxxxxx                                               ',
    'x                xx         xxxxxx                                               ',
    'x                xx         xxxxxx                       xttttttx                         ',
    'x              xxxx              x                       xxxxxxxx            ',
    'x              xxxx              x                                    ',
    'x              xxxx              x                                   ',
    'x              xxxx              x                                    ',
    'x                                x                                    ',
    'xxxxxxx                                                                            ',
    'xxxxxxx                                                                               ',
    'xxxxxxx                                                                              ',
    'xxxxxxx                                                                             ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxttttttttxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    '                                             ',
    '                                             ',
    '               z             e              ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '               Z             E              ',
    '           xxxxxxxxxxxxxxxxxxxxxxxx          ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxx5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                         o x',
    'x                                           x',
    'x    i         r                            x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x    O                               !  @   x',
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             '
  ],
  [
    'x                                             ',
    'x                                            ',
    'x               z                      e     ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x               Z                      E     ',
    'x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x=                                          x',
    'x                                           x',
    'x                                           x',
    'x              =                            x',
    'x                                           x',
    'x                                           x',
    'x                          =                x',
    'x                                           x',
    'x      O                                    x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                       L                   x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                           x',
    'x                                       @   x',
    'x                                           x',
    'x                                           x',
    'x                                        !  x',
    'x              o      xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x     i   r           xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'x                     xxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    '                                                                                               ',
    '                                             ',
    '               z                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '               Z                             ',
    '           xxxxxxxxxxxxxxxxxxxxxxxx          ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    '                                             ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                           xx',
    'x                                           xx',
    'x     e                       o     i   r   xx',
    'x                                           xx',
    'x                                           xx',
    'x                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                                                                         x',
    'x                                                                                      E  x',
    'x                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x ! @                                     O x',
    'xxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxx6xxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    'x                                                                                                                                  ',
    'x                                              ',
    'x                                          ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                          ',
    'x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    'x                                                                                                        ',
    'x                                                                                                        ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                           v                  v                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                           v                 v           ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                      v           v                  ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                               v                          v            ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                   v                   v               ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                 i    r    o                                                                          ',
    'x                                                                                                      ',
    'x                                                               xttttx                                 ',
    'x  @                                                            xxxxxx                                 ',
    'x                                                                                                      ',
    'x    z                                                                                                 ',
    'x           E                                                                   e      xttttx          ',
    'x                                                                                      xxxxxx          ',
    'x                                                                                                      ',
    'x  O Z      !                                                                                          ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    'x                                                                                                                                                                                                                                                                                            ',
    'x                                              ',
    'x               z                           ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x                                            ',
    'x               Z                           ',
    'x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                       ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                                                                                      ',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                                                                               |',
    'x                                                         ',
    'x                                                         ',
    'x                                                         ',
    'x                                                         ',
    'x                                                                                       =                                                                                                          |',
    'x                                    @      O                                                                                                                                                                                             ',
    'x                                                                                                              x                                            x',
    'x                                                                                                                                  x',
    'x                                        =                                                                                                                                                                                                       ',
    'x                                                                                                                                                                         ',
    'x                                                                            x                                                                                                             =   x          ',
    'x                                                                                                                                                                                                                               ',
    'x                                                                                                                                                      |                                                                        ',
    'x                                                                                                                                                                                                                               ',
    'x                                 ggggggggggggggggggggggggggggggtgggggggggggggggggggggggggggggggggggggggggggggggggggtgggggggggggggggggggggggggggggggggggggggggggggggggggggggtggggggggggggggggggggggggtgggggggg',
    'x                                 ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggxggggggggggggggggg',
    'x                                 ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggxggggggggggggggggggggggggggggg',
    'x                                 gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'x                                 gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'x                                 ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggxggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'x                                 gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
    'x                                 gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggxgggg',
    'x                                 gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg       !   E',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x   i    r    o    e              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                          ',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                          ',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                                                                                                                                                                     ',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                                                                                                                                                                     ',
    'x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                                                                                                                                                                     ',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxtttxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    '                                                                                     ',
    'xxxxxxxx                          i   r     o   e                            xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxxx                                                                   xxxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x             =                                                                     x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x    O                      E            Z               !                      @   x',
    'xxxxxxxx               xxxxxxx                         xxxxxxx               xxxxxxxx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'xwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwx',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                      z                            x',
    'x                                                                                   x',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx7xxxxxxxxxx8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  ],

  [
    '                                                                                     ',
    'xxxxxxxx                                z                                    xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'xxxxxxxx                                                                     xxxxxxxx',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                                   x',
    'x                                                                             o  e  x',
    'x             =                                                                     x',
    'x r                                                                                 x',
    'x                    i                                                              x',
    'x                                                                                   x',
    'x    O                      E           Z               !                       @   x',
    'xxxxxxxx      x      x      x      x      x      x      x      x      x      xxxxxxxx',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      x      x      x      x      x      x      x      x      x      x      x',
    'x      x      xxxxxxxx      x  tt  x      x      x  tt  x      xxxxxxxx      x      x'
  ]
];

export default levelMaps;
