const levelMaps = [
  // ['                                          ',
  // '                                             ',
  //  '                         z    r    o   e     ',
  //   '                         Z    @    O   E ',
  //   '                       xxxxxxxxxxxxxxxxx',
  //   '      xxxxxxxxxx                                ',
  //   '      x      i x                  ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x 0      x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',
  //   '      x        x                   ',  
  //   '      x        xxxxxxxxxxxxxxxxxx                    ',
  //   '      x                         x   ',
  //   '      x                      !  x   ',
  //   '      xxxxxxxxxxxxxxxxxxxxxxxxxxx   ',
  //   '                       ',
  //   '       1               ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  // ],

  // ['                                                    ',
  // '                                   z                  ',
  //   'x                    x                r    o   e     ',
  //   'x                    x             Z  @    O   E ',
  //   'x                    x         xxxxxxxxxxxxxxxxxxxxxxx',
  //   'x             !      x             ',
  //   'x                    x       ',
  //   'xx i                 x    ',
  //   'xx         xx   xxx  x        ',
  //   'xxxxxx               x',
  //   'xxxxxx               x   ',
  //   'xxxxxxxxxxxxxxxxxxxxxx   ',
  //   '                         ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  // ],

  // [ '   xxxxxxxxxx             z                 ',
  //   '   x        x                r    o   e     ',
  //   '   x        x             Z  @    O   E     ',
  //   '   x     x! x         xxxxxxxxxxxxxxxxxxxxxxx',
  //   '   x     xxxx             ',
  //   '   x x      x             ',
  //   '   x        x             ',
  //   '   x  x     x             ',
  //   '   x        x             ',
  //   '   x       xx             ',
  //   '   x        x             ',
  //   '   x  x     x             ',
  //   '   x        x             ',
  //   '   x       xx             ',
  //   '   x        x             ',
  //   '   x    x   x       ',
  //   '   x        x    ',
  //   '   xx       x        ',
  //   '   x        x   ',
  //   '   xxx      x   ',
  //   '   x       xx    ',
  //   '   x        x        ',
  //   '   xxxx     x',
  //   '   x i    xxx   ',
  //   '   x      xxx   ',
  //   '   xxxxxxxxxx   ',
  //   '                         ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  //   '                       ',
  // ],

  ['                                                    ',
  '                                    z                  ',
    'x                xxxxxx                     o   e     ',
    'x                xxxxxx             Z       O   E ',
    'x                xxxxxx         xxxxxxxxxxxxxxxxxxxxxxx',
    'x                xxxxxx             ',
    'x      2         xxxxxx             ',
    'x                xxxxxx             ',
    'x                xxxxxx             ',
    'x   i        r   xxxxxx      ',
    'x                xxxxxx    ',
    'xxxxxx      xxxxxxxxxxx     x        ',
    'xxxxxx      xxxxxxxxxxx  ',
    'xxxxxx @  ! xxxxxxxxxxx     ',
    'xxxxxxxxxxxxxxxxxxxxxxx   ',
    'xxxxxxxxxxxxxxxxxxxxxxx   ',
    'xxxxxxxxxxxxxxxxxxxxxxx   ',
    '        3            ',
    '                       ',
    '                       ',
    '                       ',
    '                       ',
    '                       ',
  ],
  

  [ '                                                               ',
    '                                                                 ',
    '                                                                   ',
    '                                                 x                   ',
    '        0                                   x                              ',
    '         e  z                            x                                     ',
    '      x      o                     x                                ',
    '      x i r               x                                   ',
    '      x         ! Z @ F E O                                       ',
    '      xxxxxxxxxxxxxxxxxxxxxxxpppppppppppppppppppppppppxxxxxxxxxxxxxx  ',
    '      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ',
    '                       ',
    '                       ',
    '                       ',
    '                       ',
    '                       ',
  ],

  [     "xxxxxxxxxxxxxxx                                                    ",
        "x             x                                          ",
        "x   i         x                                         ",
        "x             x                               r         ",
        "x             x                               @          ",
        "x             x                                         ",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x         0   x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x         1   x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x             x",
        "x         !   x",
        "xxxxxxxxxxxxxxx",
        "       2       ",
        "               ",
        "               "
      ],
      [
        "                                                                ",
        "                      ",   
        "                     ",
        " x                                x          x",
        " x                                x          x",
        " x                                x          x ",
        " x                                x          x         x",
        " x                               !x          x         x",
        " x                                x          x         x",
        " x   3                     4      x          x         x",
        " x                              xxx          x         x",
        " x i                              xxxxxxxxxxxx      r  x",
        " x                              @                      x",    
        " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      ],
       [  "                                                        ",
          " x                                                  x",   
          " x                                                  x",
          " x                                                  x",
          " x                                                  x",
          " x                                                  x",
          " x                       ! @                        x",
          " x   5           xxxxxxxxxxxxxxxxxx                 x",
          " x               xxxxxxxxxxxxxxxxxx                 x",
          " x i          xxxxxxxxxxxxxxxxxxxxxxxx           r  x",
          " x            xxxxxxxxxxxxxxxxxxxxxxxx              x",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],

    [ "x                                                                                                      ",
      "x             x                                          ",
      "x             x                                                                                  ",
      "x             x                                                                                    ",
      "x             x                                                                                  ",
      "x             x                                                                       xxxxxxxxxxxxxxx              ",
      "x             x                                                                       x             x           ",
      "x             x                                                                       x   !   @     x      ",
      "x             x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxx             x      ",
      "x             x      x                                 x              x                             x ",
      "x             x      x                      7          x              x                             x  ",
      "x             x      x                                 x              x                             x   ",
      "x             x      x                                 x              x                   t   t     x   ",
      "x             x      x       xxxxxxxxxxxxxxxxxxx       x              x ggggg xxxxxxxxxxxxxxxxxxxxxxx     ",
      "x             x      x ggggg x                 x       x              x ggggg x      ",
      "x             x      x ggggg x                 x       x              x ggggg x",
      "x             x      x ggggg x                 x       x              x ggggg x",
      "x             x      x ggggg x                 x       x              x ggggg x ",
      "x             xxxxxxxx ggggg x                 x       xxxxxxxxxxxxxxxx ggggg x",
      "x                      ggggg x                 x                        ggggg x                                       x",
      "x   i  r         6     ggggg x                 x                        ggggg x",
      "x                            x                 x                        ggggg x",
      "x                            x                 x                        ggggg x",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               x                        ggggg x",
      "                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
],

 [        "                                                                             ",
          " x                                                                  x        x",   
          " x                                                                  x         x",
          " x   8                                                              x         x",
          " x                                                                  x        x",
          " x   i    r                                                         x            x",
          " x                                                                  x        x",
          " xxxxxxxxxxxxx           xxx             xxx                    ! @ x                    x",
          " xxxxxxxxxxxxx                                              xxxxxxxxx                     x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx                   x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwww9wwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxppppppppppppppppppppppppppppppppppppppppppxxxxxxxxxxxxx",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
[         "x             x                                            ",
          "x    i    r   x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "xp  ppppppppppx",
          "x             x",
          "x   ~         x",
          "x             x          #",
          "x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x                |   v   |   v   |   v  =|   |   v =   x",
          "x                  v   v    v   v   v  =v   |   v   =  x",
          "x     !                                            @   x",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
],

      [  "                                                                                             r  ",
          " x                                                                                        x  @ x",   
          " x                                                                                        xxxxxx",
          " x                                                               x",
          " x               x                                x              x",
          " x                              x                          x     x",
          " x           x                            x                      x",
          " x                      x                            x           x",
          " x                                           x                   x",
          " x               $                  x                            x",
          " x                            x                           x      x",
          " x i                                                             x",
          " x                                                           !   x",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],

      [  "                                                           r  ",
          " x                                     x                x  @ x",   
          " x                                     x                xxxxxx",
          " x                                     x",
          " x              xhh ! hhx              x",
          " x             xhhhh hhhhx     t       x",
          " x             xhhhhhhhhhx             x",
          " x             xxhhhhhhhxx             x",
          " x              xxhhhhhxx              x",
          " x   %           xxhhhxx    t          x",
          " x                xxhxx                x",
          " x i               xxx                 x",
          " x                                     x",    
          " x                             t       x",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],
[         "                                                                          r      ",
          " x                                                                  x     @     x",   
          " x                                                                  x   xxxxxxxxx         x",
          " x   ^                                                              x         x",
          " x                                                                  x        x",
          " x   i                                                              x            x",
          " x                                                                  x        x",
          " xxxxxxxxxxxxx           xxx             xxx                    !   x                    x",
          " xxxxxxxxxxxxx                                              xxxxxxxxx                     x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx                   x",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxx",
          " xxxxxxxxxxxxxppppppppppppppppppppppppppppppppppppppppppxxxxxxxxxxxxx",    
          " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ],

[       "xxxxxxxxxxxxxxxxxx                                                       ",
        "x                x                                          ",
        "x      !         x                                         ",
        "x                x                               r         ",
        "x                x                               @          ",
        "x                x                                         ",
        "x                x",
        "x                x                                          ",
        "x                x                                        ",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x   i    &       x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x                xxxxxxxxxxxxxxxx",
        "x               *               x",
        "x                               x",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
],

      [   " )                                                      @ ",
          "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x                                         x",
          "x                                      !  x",
          "x             xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x             x",
          "x    i    r   x",
          "x (           x",
          "xxxxxxxxxxxxxxx"]
    
  ];
    
    
export default levelMaps;